#! /bin/sh

sxhkd &

lxappearance &

killall lxappearance &

# ~/lemonbar.sh | lemonbar -B "#2e3440" -F "#e5e9f0" -f "xft:Mononoki Nerd Font:pixelsize=12" &

polybar bspwm &

xautolock -time 10 -locker slock &

compton &

nitrogen --restore &

alacritty &

steam -silent &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a emacs state=tile
